### ISSUE TITLE
Jpaint Mac pixel size display

### ISSUE THREAD

**Issue by PhilipN27** [a-r-t/JPaint#11]
On the mac version of Jpaint there is no way for the user to see how big the canvas is by pixel(x,y). The select tool as well cannot display what pixel size is inside of it.

**Comment by a-r-t** [comment]
Your requested feature has been implemented into the newest release (v1.0.0), which can be downloaded [here](https://github.com/a-r-t/JPaint/releases/tag/v1.0.0).
